### ISSUE TITLE
recognize `@` as a pointer

### ISSUE THREAD

**Issue by ezio416** [Hazelight/vscode-unreal-angelscript-formatter#2]
I just started using this extension, but for Openplanet Angelscript which is a bit different from the flavor used for Unreal. We don't have the classic pointer symbol (`*`), instead we use `@` for handles which is a very similar concept but not exactly the same. I mainly want this to be recognized for the option `PointerAlignment` since it is much more common to have a declaration like `Json::Value@ value;`, however the extension always formats it like `Json::Value @value;`. The latter is still valid but makes less sense for our uses.

If you feel like this is impossible or breaks something for Unreal Angelscript, please feel free to close this.

**Comment by nils-soderman** [comment]
Hi,

Since this extension is specifically meant for formatting Unreal Engine AngelScript code, I don't think it makes sense to start adding rules for other versions of AngelScript.

However, you could make a fork/copy of this extension and repurpose it for Openplanet AngelScript.
The way I've dealt with AngelScript not 100% aligning with C++ rules is by filtering out all unwanted changes, this is done by the `allowEdit` method found in [src/formatter.ts](https://github.com/Hazelight/vscode-unreal-angelscript-formatter/blob/5cd3eaffc7390c55df05df76acd853c634acc642/src/formatter.ts#L43).

To fix this you could move this part out of the if block _(to row 47)_, so `text` is always available: 
```typescript
const testRange = new vscode.Range(
    new vscode.Position(editRange.start.line, editRange.start.character - 1),
    new vscode.Position(editRange.end.line, line.range.end.character)
 );
const text = document.getText(testRange);
```

Then add a rule after it to prevent @ from being moved, e.g:
```typescript
if (text.match(/^@\s|^.@\s/))
    return false;
```

This will not enforce @ to be on the left side, but it won't move it to the right either.

**Comment by ezio416** [comment]
Fair enough, and thanks for the info! I will have to look into that
